name: "CI - Non Prod"
on:
  pull_request:
  push:

# Silly `uses` syntax to work around this issue -> https://github.com/github/feedback/discussions/10679
jobs:
  code:
    # todo: replace with generic build+test command for micronaut. If people need to customize, they can.
    # But initially. everyone should just have a single line here
    uses: nckackerman/nckackerman.github.io/.github/workflows/reuseable_build.yml@master
    with:
      commit-hash: hash

  # todo: replace with generic security command for micronaut. If people need to customize, they can.
  # But initially. everyone should just have a single line here
  security:
    uses: nckackerman/nckackerman.github.io/.github/workflows/reuseable_security.yml@master
    with:
      image: test

  # todo: create a release and push to artifactory
  release-create:
    needs: [code, security]
    uses: nckackerman/nckackerman.github.io/.github/workflows/reuseable_security.yml@master
    with:
      image: test

  # deploy to dev + qa
  dev:
    needs: [release-create]
    uses: nckackerman/nckackerman.github.io/.github/workflows/reuseable_deploy.yml@master
    with:
      env: DEV
      tag: DEV

  qa:
    needs: [dev]
    uses: nckackerman/nckackerman.github.io/.github/workflows/reuseable_deploy.yml@master
    with:
      env: QA
      tag: QA

  # optionally, trigger the prod workflow by tagging a branch