Sname: "CI - Prod"
on:
  pull_request:
  push:

# Silly `uses` syntax to work around this issue -> https://github.com/github/feedback/discussions/10679
# deploy to staging and prod
jobs:
  prod:
    uses: nckackerman/nckackerman.github.io/.github/workflows/reuseable_deploy.yml@master
    with:
      env: PROD
      tag: PROD