name: "CI"
on:
  pull_request:
  push:

# Silly `uses` syntax to work around this issue -> https://github.com/github/feedback/discussions/10679
jobs:
  code:
    uses: nckackerman/nckackerman.github.io/.github/workflows/reuseable_build.yml@master
    with:
      commit-hash: hash

  security:
    uses: nckackerman/nckackerman.github.io/.github/workflows/reuseable_security.yml@master
    with:
      image: test

  release-create:
    needs: [code, security]
    uses: nckackerman/nckackerman.github.io/.github/workflows/reuseable_security.yml@master
    with:
      image: test

  dispatch:
    needs: code
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          repository: nckackerman/nckackerman.github.io
          event-type: test-event
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'

  dev:
    needs: [release-create]
    uses: nckackerman/nckackerman.github.io/.github/workflows/reuseable_deploy.yml@master
    with:
      env: DEV
      tag: DEV

  qa:
    needs: [dev]
    uses: nckackerman/nckackerman.github.io/.github/workflows/reuseable_deploy.yml@master
    with:
      env: QA
      tag: QA

  uat:
    needs: [qa]
    uses: nckackerman/nckackerman.github.io/.github/workflows/reuseable_deploy.yml@master
    with:
      env: UAT
      tag: UAT

  prod:
    needs: [uat]
    uses: nckackerman/nckackerman.github.io/.github/workflows/reuseable_deploy.yml@master
    with:
      env: PROD
      tag: PROD