name: "CI"
on:
  pull_request:
  push:

# Silly `uses` syntax to work around this issue -> https://github.com/github/feedback/discussions/10679
jobs:
  build:
    uses: nckackerman/nckackerman.github.io/.github/workflows/reuseable_build.yml@master
    with:
      commit-hash: hash
  security:
    uses: nckackerman/nckackerman.github.io/.github/workflows/reuseable_security.yml@master
    with:
      image: test
  # Silly `uses` syntax to work around this issue -> https://github.com/github/feedback/discussions/10679
  deploy:
    needs: security
    uses: nckackerman/nckackerman.github.io/.github/workflows/reuseable_deploy.yml@master
    with:
      env: DEV-TEST
      tag: TAG-TEST