name: POC

on:
  workflow_dispatch:

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - name: push
        run: |
          curl -X POST -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/nckackerman/nckackerman.github.io/actions/runs/2210498078/pending_deployments -d '{"state": approved, "comment": gha-approved}'