name: "Reusable/Security"

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      image:
        required: true
        description: image hash to security scan
        type: string

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: |
          echo "This is where we would run security scans"