name: "Reusable/Build"
on:
  workflow_dispatch:
    inputs:
      name: env
        type: choice
        description: env to deploy
        required: true
        options:
          - dev
          - qa
          - uat
          - prod
  workflow_call:
    inputs:
      commit-hash:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: |
          echo "This is where we would build code"