name: "Reusable/Deploy"

on:
  workflow_dispatch:
    inputs:
      name:
        type: environment
        description: env to deploy
        required: true
  workflow_call:
    inputs:
      env:
        required: true
        description: env - dev/qa/uat/prod
        type: string
      tag:
        required: false
        description: tag - test description
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: |
          echo "passed in env - ${{inputs.env}} \n and passed in tag - ${{inputs.tag}}"