name: "Reusable/Deploy"

on:
  workflow_dispatch:
    inputs:
      name: env
        type: choice
        description: env to deploy
        required: true
        options:
          - dev
          - qa
          - uat
          - prod
  workflow_call:
    inputs:
      env:
        required: true
        description: env - dev/qa/uat/prod
        type: string
      tag:
        required: false
        description: tag - test description
        type: string

jobs:
  dummy_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: |
          echo "passed in env - ${{inputs.env}} \n and passed in tag - ${{inputs.tag}}"
          
  dummy_post_deploy:
    runs-on: ubuntu-latest
    needs: [ dummy_deploy ]
    steps:
      - name: post deploy
        run: |
          echo "post deploy"